steps:
- task: esfadevops.DependencyCheck.custom-dependency-check.DependencyCheck@2
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: 'Dependency Check'
  inputs:
    enableVulnerabilityFilesMaintenance: false
    logAnalyticsWorkspaceId: '$(LogAnalyticsWorkspaceId)'
    logAnalyticsWorkspaceKey: '$(LogAnalyticsWorkspaceKey)'
    enableSelfHostedVulnerabilityFiles: true
    readStorageAccountContainerSasUri: '$(DependencyCheckSasUri)'
    excludedScanPathPatterns: '$(DependencyCheckExcludedScanPathPatterns)'
    severityThreshold: '$(DependencyCheckSeverityThreshold)'
    dependencyCheckDashboardUrl: '$(DependencyCheckDashboardUrl)'
