trigger:
  batch: true
  branches:
    include:
      - "master"

pr: none

stages:
  - stage: Versioning
    dependsOn: []
    jobs:
    - job: GitVersion
      displayName: Version
      pool:
        name: DAS - Continuous Integration
      steps:
        - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
          displayName: GitVersion
          inputs:
            configFilePath: GitVersion.yml

  - stage: Release
    dependsOn: Versioning
    #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
    - deployment: GitHubRelease
      displayName: Create Release in GitHub
      pool:
        name: DAS - Continuous Deployment Agents
      environment: GitHub
      strategy:
        runOnce:
          deploy:
            steps:
              - task: GitHubRelease@0
                inputs:
                  isDraft: true
                  gitHubConnection: SkillsFundingAgency
                  repositoryName: $(Build.Repository.Name)
                  action: create
                  target: $(Build.SourceVersion)
                  tagSource: manual
                  tag: $(Build.BuildNumber)
                  addChangeLog: true
                  assets: |
                    $(Build.ArtifactStagingDirectory)/**/*.yml
                    $(Build.ArtifactStagingDirectory)/**/*.json
