parameters:
  ServiceConnection:
  AppRegistrationObjectId:

steps:
- task: AzurePowerShell@5
  displayName: 'Create 1 hour lifetime app registration client secret'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: inlineScript
    inline: |
      $StartDate = Get-Date
      $EndDate = $StartDate.AddHours(1)
      $ClientSecret = New-AzADAppCredential -ObjectId ${{ parameters.AppRegistrationObjectId }} -StartDate $StartDate -EndDate $EndDate
      Write-Output "Setting variables AppRegistrationTemporaryClientSecretId and AppRegistrationTemporaryClientSecret"
      Write-Output "##vso[task.setvariable variable=AppRegistrationTemporaryClientSecretId;isreadonly=true]$($ClientSecret.KeyId)"
      Write-Output "##vso[task.setvariable variable=AppRegistrationTemporaryClientSecret;isreadonly=true;issecret=true]$($ClientSecret.SecretText)"
      Write-Output "Wait 1 minute in order for newly created client secret to be used successfully."
      Start-Sleep -Seconds 60
    azurePowerShellVersion: LatestVersion