parameters:
  ServiceConnection:
  ResourceName:
  Tenant:
  IsMultiRepoCheckout: false
  DryRun: $false

steps:
- checkout: das-platform-automation
- task: AzureCLI@2
  displayName: Azure CLI - app role assignments
  condition: and(succeeded(), in(variables['Resources.Pipeline.das-employer-config.SourceBranch'], 'master', 'main'))
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: pscore
    ${{ if eq(parameters.IsMultiRepoCheckout, false)  }}:
      scriptPath: Infrastructure-Scripts/Set-AppRoleAssignments/Set-AppRoleAssignments.ps1
    ${{ if eq(parameters.IsMultiRepoCheckout, true)  }}:
      scriptPath: das-platform-automation/Infrastructure-Scripts/Set-AppRoleAssignments/Set-AppRoleAssignments.ps1
    arguments:
      -AppRegistrationConfigurationFilePath $(Pipeline.Workspace)/das-employer-config/Configuration/app-role-assignments/config.json
      -ResourceName ${{ parameters.ResourceName }}
      -Tenant ${{ parameters.Tenant }}
      -DryRun ${{ parameters.DryRun }}