parameters:
  ServiceConnection:
  AppRegistrationObjectId:
  AppRegistrationClientSecretId:
  AlwaysRun: true

steps:
- task: AzurePowerShell@5
  displayName: 'Delete app registration client secret'
  ${{ if eq(parameters.AlwaysRun, true) }}:
    condition: always()
  ${{ if ne(parameters.AlwaysRun, true) }}:
    condition: succeeded()
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: inlineScript
    inline: |
      Write-Output "Deleting client secret with ID ${{ parameters.AppRegistrationClientSecretId }} from app registration with object ID ${{ parameters.AppRegistrationObjectId }}"
      Remove-AzADAppCredential -ObjectId ${{ parameters.AppRegistrationObjectId }} -KeyId ${{ parameters.AppRegistrationClientSecretId }}
    azurePowerShellVersion: LatestVersion