parameters:
  ServiceConnection:
  AppServiceName:
  DryRun: $false

steps:
- task: AzureCLI@2
  displayName: Azure CLI - app role assignments
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: pscore
    scriptPath: $(Pipeline.Workspace)/das-infrastructure-config/Configuration/app-role-assignments/scripts/Set-AppRoleAssignments.ps1
    arguments:
      -AppServiceName ${{ parameters.AppServiceName }}
      -DryRun ${{ parameters.DryRun }}
