parameters:
  ServiceConnection:
  AppServiceName:
  ScriptPath:
  DryRun: $false

steps:
- task: AzureCLI@2
  displayName: Azure CLI - app role assignments
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: pscore
    scriptPath: ${{ parameters.ScriptPath }}
    arguments:
      -AppServiceName ${{ parameters.AppServiceName }}
      -DryRun ${{ parameters.DryRun }}
