parameters:
  ServiceConnection:
  ResourceName:
  Tenant:
  DryRun: $false

steps:
- checkout: das-platform-automation
- task: AzureCLI@2
  displayName: Azure CLI - app role assignments
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: pscore
    scriptPath: Infrastructure-Scripts/Set-AppRoleAssignments/Set-AppRoleAssignments.ps1
    arguments:
      -AppRegistrationConfigurationFilePath $(Pipeline.Workspace)/das-employer-config/Configuration/app-role-assignments/config.json
      -ResourceName ${{ parameters.ResourceName }}
      -Tenant ${{ parameters.Tenant }}
      -DryRun ${{ parameters.DryRun }}
