parameters:
  ServiceConnection:
  ResourceEnvironmentName:
  AppServiceName:
  ScriptPath:
  - name: DryRun
    type: boolean
    default: false


steps:
- task: AzureCLI@2
  displayName: Azure CLI - app role assignments
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptType: pscore
    scriptPath: ${{ parameters.ScriptPath }}
    arguments:
      -Environment ${{ parameters.ResourceEnvironmentName }}
      -AppServiceName ${{ parameters.AppServiceName }}
      -DryRun ${{ parameters.DryRun }}
