parameters:
  AksClusterName:
  AksResourceGroupName:
  AzureSubscription:
  KubectlVersion: 
  ManifestFile: 

steps:
- task: KubectlInstaller@0
  displayName: 'Install Kubectl ${{ parameters.KubectlVersion }}'
  inputs:
    kubectlVersion: ${{ parameters.KubectlVersion }}
- task: Kubernetes@1
  displayName: 'kubectl apply'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '${{parameters.AzureSubscription}}'
    azureResourceGroup: '${{parameters.AksResourceGroupName}}'
    kubernetesCluster: '${{parameters.AksClusterName}}'
    useClusterAdmin: true
    command: apply
    useConfigurationFile: true
    configuration: '${{parameters.ManifestFile}}'