parameters:
  ServiceConnection:
  SourcePath:
  TargetFileName: '*.schema.json'
  ConfigurationSecrets: {}
  TableName: 'Configuration'

steps:
- checkout: das-platform-automation
- task: AzurePowerShell@5
  displayName: New-ConfigurationTableEntry
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    scriptPath: das-platform-automation/Infrastructure-Scripts/New-ConfigurationTableEntry/New-ConfigurationTableEntry.ps1
    scriptArguments:
      -SourcePath ${{ parameters.SourcePath }}
      -TargetFilename ${{ parameters.TargetFileName }}
      -StorageAccountName '$(ConfigurationStorageAccountName)'
      -StorageAccountResourceGroup '$(SharedEnvResourceGroup)'
      -EnvironmentName '$(EnvironmentName)'
    azurePowerShellVersion: LatestVersion
    pwsh: true
  env: ${{ parameters.ConfigurationSecrets }}
