parameters:
  dashboardUID: ''
  panelId: 0
  tags: []  # Define tags as an array
  text: ''  # Ensure text is passed
  BearerToken: ''  # Ensure BearerToken is passed
  IsMultiRepoCheckout: false

steps:
- checkout: self
- task: PowerShell@2
  displayName: "Create Grafana Annotation - ${{ parameters.dashboardUID }}"
  inputs:
    targetType: 'filePath'
    ${{ if eq(parameters.IsMultiRepoCheckout, false) }}:
      filePath: Infrastructure-Scripts/New-GrafanaDashboardAnnotation.ps1
    ${{ if eq(parameters.IsMultiRepoCheckout, true) }}:
      filePath: das-platform-automation/Infrastructure-Scripts/New-GrafanaDashboardAnnotation.ps1
    arguments: |
      -dashboardUID ${{ parameters.dashboardUID }} `
      -panelId ${{ parameters.panelId }} `
      -tags @(${{
        parameters.tags | join(',')
      }}) `  # Pass tags as a comma-separated string
      -text "${{ parameters.text }}" `  # Ensure text is passed
      -token (ConvertTo-SecureString "${{ parameters.BearerToken }}" -AsPlainText -Force)  # Ensure BearerToken is passed
    pwsh: true
