parameters:
  AksClusterName:
  AksResourceGroupName:
  AzureServiceConnection:
  KubectlVersion:
  ManifestFile:
  Namespace:
  # Allowed values are 'json', 'yaml' and 'name'
  OutputFormat: 'name'
  VerifyDeployment: false
  DeploymentName: ''

steps:
- task: KubectlInstaller@0
  displayName: 'Install Kubectl ${{ parameters.KubectlVersion }}'
  inputs:
    kubectlVersion: ${{ parameters.KubectlVersion }}
- task: Kubernetes@1
  displayName: 'kubectl apply ${{parameters.ManifestFile}}'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '${{parameters.AzureServiceConnection}}'
    azureResourceGroup: '${{parameters.AksResourceGroupName}}'
    kubernetesCluster: '${{parameters.AksClusterName}}'
    useClusterAdmin: true
    namespace: ${{ parameters.Namespace }}
    command: apply
    arguments: -f ${{parameters.ManifestFile}}
    outputFormat: ${{parameters.OutputFormat}}
- task: Kubernetes@1
  condition: and(succeeded(), eq(${{parameters.VerifyDeployment}}, 'true'))
  displayName: get rollout status for ${{parameters.DeploymentName}}
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '${{parameters.AzureServiceConnection}}'
    azureResourceGroup: '${{parameters.AksResourceGroupName}}'
    kubernetesCluster: '${{parameters.AksClusterName}}'
    useClusterAdmin: true
    namespace: ${{ parameters.Namespace }}
    command: rollout
    arguments: status deployment ${{parameters.DeploymentName}}
