parameters:
  AksClusterName:
  AksResourceGroupName:
  AzureServiceConnection:
  Namespace:
  # The kubectl arguments used to create the secret - https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret
  # eg '--from-literal=mySecretName=$(MySecretVariable)'
  SecretArguments:
  SecretName:
  KubectlVersion: 'latest'

steps:
- task: KubectlInstaller@0
  displayName: Install Kubectl ${{ parameters.KubectlVersion }}
  inputs:
    kubectlVersion: ${{ parameters.KubectlVersion }}
- task: Kubernetes@1
  displayName: kubectl create ${{ parameters.SecretName }} secret
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: ${{ parameters.AzureServiceConnection }}
    azureResourceGroup: ${{ parameters.AksResourceGroupName }}
    kubernetesCluster: ${{ parameters.AksClusterName }}
    useClusterAdmin: true
    namespace: ${{ parameters.Namespace }}
    secretType: generic
    secretArguments: ${{ parameters.SecretArguments }}
    secretName: ${{ parameters.SecretName }}