parameters:
  AzureSubscription:
  ServerName:
  DatabaseName:
  SqlUsername:
  SqlPassword:
  DacpacFile:
  AdditionalArguments: ''

steps:
- task: SqlAzureDacpacDeployment@1
  displayName: Execute Azure SQL DacpacTask
  condition: ne(variables.BuildToRunAdditionalArgumentsOn, variables['Build.Buildnumber'])
  inputs:
    AzureSubscription: ${{ parameters.AzureSubscription }}
    ServerName: ${{ parameters.ServerName }}
    DatabaseName: ${{ parameters.DatabaseName }}
    SqlUsername: ${{ parameters.SqlUsername }}
    SqlPassword: ${{ parameters.SqlPassword }}
    DacpacFile: ${{ parameters.DacpacFile }} 

- task: SqlAzureDacpacDeployment@1
  displayName: Execute Azure SQL DacpacTask
  condition: eq(variables.BuildToRunAdditionalArgumentsOn, variables['Build.BuildNumber'])
  inputs:
    AzureSubscription: ${{ parameters.AzureSubscription }}
    ServerName: ${{ parameters.ServerName }}
    DatabaseName: ${{ parameters.DatabaseName }}
    SqlUsername: ${{ parameters.SqlUsername }}
    SqlPassword: ${{ parameters.SqlPassword }}
    DacpacFile: ${{ parameters.DacpacFile }}
    AdditionalArguments: ${{ parameters.AdditionalArguments }}