parameters:
  EnvironmentId:
  PipelineName:
  RunId:
  SleepTime: 20
  RetryLimit: 30

steps:
- checkout: das-platform-automation
- task: PowerShell@2
  displayName: Wait for running deployments
  inputs:
    filePath: das-platform-automation/Infrastructure-Scripts/Wait-AzureDevOpsDeployment.ps1
    arguments:
      -AzureDevOpsOrganisationUri "$(System.CollectionUri)" `
      -AzureDevOpsProjectName $(System.TeamProjectId) `
      -EnvironmentId ${{ parameters.EnvironmentId }} `
      -PipelineName "${{ parameters.PipelineName }}" `
      -RunId ${{ parameters.RunId }} `
      -SleepTime ${{ parameters.SleepTime }} `
      -RetryLimit ${{ parameters.RetryLimit }}
    pwsh: true
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
