parameters:
  ServiceConnection: ''
  AppServiceName: ''
  DeploymentPackagePath: ''
  VirtualApplication: ''
  DeploymentType: webDeploy

steps:

- task: AzureAppServiceManage@0
  displayName: 'Stop all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    Action: 'Stop all continuous webjobs'
    WebAppName: ${{ parameters.AppServiceName }}

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: $(AppServiceName)'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    WebAppName: ${{ parameters.AppServiceName }}
    Package: ${{ parameters.DeploymentPackagePath }}
    ${{ if ne(parameters.VirtualApplication, '') }}:
      VirtualApplication: ${{ parameters.VirtualApplication }}
    DeploymentType: ${{ parameters.DeploymentType }}
    AppSettings: '-WEBSITE_ENABLE_SYNC_UPDATE_SITE 1'

- task: AzureAppServiceManage@0
  displayName: 'Start all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    Action: 'Start all continuous webjobs'
    WebAppName: ${{ parameters.AppServiceName }}

