parameters:
  ServiceConnection: ''
  AppServiceName: ''
  DeploymentPackagePath: ''
  VirtualApplication: ''
  ResourceGroupName: ''
  DeploymentType: webDeploy

steps:

- task: AzurePowerShell@5
  displayName: 'Stop all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    ScriptType: InlineScript
    Inline: |
      $appSettings = (Get-AzWebApp -ResourceGroupName ${{ parameters.ResourceGroupName }} -Name ${{ parameters.AppServiceName }}).SiteConfig.AppSettings
      $settingsHashtable = @{}
      foreach ($setting in $appSettings) {
          $settingsHashtable[$setting.Name] = $setting.Value
      }
      $settingsHashtable["WEBJOBS_STOPPED"] = "1"
      Set-AzWebApp -ResourceGroupName ${{ parameters.ResourceGroupName }} -Name ${{ parameters.AppServiceName }} -AppSettings $settingsHashtable
    azurePowerShellVersion: LatestVersion

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    WebAppName: ${{ parameters.AppServiceName }}
    Package: ${{ parameters.DeploymentPackagePath }}
    ${{ if ne(parameters.VirtualApplication, '') }}:
      VirtualApplication: ${{ parameters.VirtualApplication }}
    DeploymentType: ${{ parameters.DeploymentType }}
    AppSettings: '-WEBSITE_ENABLE_SYNC_UPDATE_SITE 1'

- task: AzurePowerShell@5
  displayName: 'Start all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    ScriptType: InlineScript
    Inline: |
      $appSettings = (Get-AzWebApp -ResourceGroupName ${{ parameters.ResourceGroupName }} -Name ${{ parameters.AppServiceName }}).SiteConfig.AppSettings
      $settingsHashtable = @{}
      foreach ($setting in $appSettings) {
          $settingsHashtable[$setting.Name] = $setting.Value
      }
      $settingsHashtable["WEBJOBS_STOPPED"] = "0"
      Set-AzWebApp -ResourceGroupName ${{ parameters.ResourceGroupName }} -Name ${{ parameters.AppServiceName }} -AppSettings $settingsHashtable
    azurePowerShellVersion: LatestVersion