parameters:
  ServiceConnection: ''
  AppServiceName: ''
  DeploymentPackagePath: ''
  VirtualApplication: ''
  DeploymentType: webDeploy

steps:

- task: AzureAppServiceManage@0
  displayName: 'Stop all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    Action: 'Stop all continuous webjobs'
    WebAppName: ${{ parameters.AppServiceName }}

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    WebAppName: ${{ parameters.AppServiceName }}
    packageForLinux: ${{ parameters.DeploymentPackagePath }}
    enableCustomDeployment: true
    DeploymentType: ${{ parameters.DeploymentType }}
    TakeAppOfflineFlag: false
    AppSettings: '-WEBSITE_ENABLE_SYNC_UPDATE_SITE 1'

- task: AzureAppServiceManage@0
  displayName: 'Start all continuous webjobs - ${{ parameters.AppServiceName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    Action: 'Start all continuous webjobs'
    WebAppName: ${{ parameters.AppServiceName }}