parameters:
  AzureSubscription: ''
  Environment: ''
  AppServiceName: ''
  DeploymentPackagePath: ''

jobs:
- deployment: DeployApp_${{ parameters.AppServiceName }}
  condition: succeeded()
  pool:
    name: DAS - Continuous Deployment
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureRmWebAppDeployment@3
          displayName: Deploy Staging Slot - ${{ parameters.AppServiceName }}
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            appType: webApp
            WebAppName: ${{ parameters.AppServiceName }}
            DeployToSlotFlag: true
            ResourceGroupName: $(ResourceGroupName)
            SlotName: staging
            Package: ${{ parameters.DeploymentPackagePath }}
            UseWebDeploy: true
            RemoveAdditionalFilesFlag: true

        - task: AzureAppServiceManage@0
          displayName: Start Staging Slot - ${{ parameters.AppServiceName }}
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            Action: Start Azure App Service
            WebAppName: ${{ parameters.AppServiceName }}
            ResourceGroupName: $(ResourceGroupName)
            SpecifySlotOrASE: true
            Slot: staging

        - task: AzureAppServiceManage@0
          displayName: Start Swap Slots - ${{ parameters.AppServiceName }}
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            Action: Start Swap With Preview
            WebAppName: ${{ parameters.AppServiceName }}
            ResourceGroupName: $(ResourceGroupName)
            SourceSlot: staging

        - task: AzureAppServiceManage@0
          displayName: Complete Swap Slot
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            Action: Complete Swap
            WebAppName: ${{ parameters.AppServiceName }}
            ResourceGroupName: $(ResourceGroupName)
            SourceSlot: staging

        - task: AzureAppServiceManage@0
          displayName: Stop Staging Slot - ${{ parameters.AppServiceName }}
          condition: always()
          inputs:
            azureSubscription:  ${{ parameters.AzureSubscription }}
            Action: Stop Azure App Service
            WebAppName: ${{ parameters.AppServiceName }}
            SpecifySlotOrASE: true
            ResourceGroupName: $(ResourceGroupName)
            Slot: staging
