parameters:
  AzureSubscription: ''
  Environment: ''
  TemplatePath: ''
  ParametersPath: ''
  ConfigSchemaPath: ''
  TemplateSecrets: {}

jobs:
- deployment: DeployInfrastructure
  pool:
    name: DAS - Continuous Deployment
  environment: ${{ parameters.Environment }}
  workspace:
    clean: all
  strategy:
    runOnce:
      deploy:
        steps:
        # - task: DownloadGitHubRelease@0
        #   displayName: Download das-platform-automation Github Artifact
        #   inputs:
        #     connection: GitHub (SFA)
        #     userRepository: SkillsFundingAgency/das-platform-automation
        #     defaultVersionType: specificTag
        #     version: 4.1.0
        - checkout: das-platform-automation

        - task: PowerShell@2
          displayName: Generate Parameters File
          inputs:
            #filePath: $(System.ArtifactsDirectory)/New-ParametersFile.ps1
            filePath: Infrastructure-Scripts/New-ParametersFile.ps1@das-platform-automation
            arguments: >
              -TemplateFilePath ${{ parameters.TemplatePath }}
              -ParametersFilePath ${{ parameters.ParametersPath }}
            pwsh: true
          env: ${{ parameters.TemplateSecrets }}

        - task: AzurePowerShell@5
          displayName: 'Create and Tag Resource Group'
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            #ScriptPath: $(System.ArtifactsDirectory)/Set-AzResourceGroupTags.ps1
            ScriptPath: Infrastructure-Scripts/Set-AzResourceGroupTags.ps1@das-platform-automation
            ScriptArguments: '-ResourceGroupName "$(ResourceGroupName)" -Tags "$(Tags)"'
            azurePowerShellVersion: LatestVersion

        - task: AzureResourceGroupDeployment@2
          displayName: Azure Deployment - Deploy resources to $(ResourceGroupName)
          inputs:
            azureSubscription: ${{ parameters.AzureSubscription }}
            resourceGroupName: $(ResourceGroupName)
            location: West Europe
            csmFile: ${{ parameters.TemplatePath }}
            csmParametersFile: ${{ parameters.ParametersPath }}
            deploymentOutputs: ARMOutputs

        - task: esfadevops.ARMTemplateOutputs.custom-build-task.ARMTemplateOutputs@0
          displayName: Convert ARM Template Outputs to Variables
          inputs:
            ARMOutputs: $(ARMOutputs)

        - template: ../step/generate-config.yml
          parameters:
            AzureSubscription: ${{ parameters.AzureSubscription }}
            SourcePath: ${{ parameters.ConfigSchemaPath }}
            TargetFileName: '*.schema.json'
            TableName: Configuration
