parameters:
  ServiceConnection: ''
  SubscriptionId: ''
  Location: ''
  Environment: ''
  TemplatePath: ''
  ParametersPath: ''
  ConfigSchemaPath: ''
  TemplateSecrets: {}

jobs:
- deployment: DeployInfrastructure
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  workspace:
    clean: all
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../step/arm-deploy.yml
          parameters:
            Location: ${{ parameters.Location }}
            ParametersPath: ${{ parameters.ParametersPath }}
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            TemplatePath: ${{ parameters.TemplatePath }}
            TemplateSecrets: ${{ parameters.TemplateSecrets }}
            
        - template: ../step/generate-config.yml
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: ${{ parameters.ConfigSchemaPath }}
            TargetFileName: '*.schema.json'
            TableName: Configuration
