
parameters:
- name: AzureSubscription
- name: DacpacFile
- name: DatabaseNameArmOutput
  default: DatabaseName
- name: DependsOn
  default: DeployResources
- name: Environment
  type: string
  values:
  - AT
  - TEST
  - TEST2
  - PP
  - PROD
  - MO
  - DEMO
- name: Pool
  type: string
  default: DAS - Continuous Deployment Agents
- name: RunBlockOnPossibleDataLoss
  type: boolean
- name: ServerName
- name: SqlUsername
- name: SqlPassword

jobs:
- job: WaitForValidation
  pool: server
  dependsOn: ${{ parameters.DependsOn }}
  condition: succeeded()
  timeoutInMinutes: 5 
  steps:
  - task: ManualValidation@0
    condition: and(eq('${{ parameters.Environment }}', 'PROD'), eq(${{ parameters.RunBlockOnPossibleDataLoss }}, true))
    timeoutInMinutes: 5 
    inputs:
      instructions: 'WARNING!. /p:BlockOnPossibleDataLoss=false command will run on SQL DACPAC deployment and might result in data loss. Are you sure you want to continue?'
      onTimeout: 'reject'

- deployment: RunSqlDacpac
  pool:
    name: ${{ parameters.Pool }}
  environment: ${{ parameters.Environment }}
  dependsOn: 
  - WaitForValidation
  - ${{ parameters.DependsOn }}
  condition: succeeded()
  variables:
    DatabaseNameVariable: $[ dependencies.${{ parameters.DependsOn }}.outputs['${{ parameters.DependsOn }}.ArmOutputs${{ parameters.Environment }}.${{ parameters.DatabaseNameArmOutput }}'] ]
  strategy:
    runOnce:
      deploy:
        steps:
        - task: SqlAzureDacpacDeployment@1
          displayName: Execute Azure SQL DacpacTask
          inputs:
            AzureSubscription: ${{ parameters.AzureSubscription }}
            ServerName: ${{ parameters.ServerName }}
            DatabaseName: $(DatabaseNameVariable)
            SqlUsername: ${{ parameters.SqlUsername }}
            SqlPassword: ${{ parameters.SqlPassword }}
            DacpacFile: ${{ parameters.DacpacFile }}
            ${{ if eq(parameters.RunBlockOnPossibleDataLoss, true) }}:
              AdditionalArguments: /p:BlockOnPossibleDataLoss=false